### ISSUE TITLE
instance-specific portion of URL in _JIRA_API should be read from config file

### ISSUE THREAD

**Issue by ggruen** [cloudily/jira#1]
Hey Tony,

Love this!

Since this is on github, _JIRA_API should be instance-agnostic (e.g. read from the user_credentials file or similar).

I may take a crack at changing this and submitting a pull request, but thought I'd get it in here in case you or someone else gets to it first. :)

**Comment by cloudily** [comment]
Was planning on adding this.  Can be done by creating a `.jirarc` file and checking if the vars are already set in the bootstrap.

**Comment by cloudily** [comment]
Resolved via 14975cda1db6b5e8e552376b943c99c2fc1dd6c1
