### ISSUE TITLE
It would be nice if time could be specified in HH:MM format

### ISSUE THREAD

**Issue by ggruen** [cloudily/jira#2]
To make entering time easy if, say, one needs to enter time into JIRA and into another system that takes time in HH:MM format, it'd be nice if the time format could be specified in HH:MM format and converted to seconds.

Here's a Perl routine that converts to hours - it could be adapted to bash and added to _jira.to_seconds (e.g. if time ends with a number and contains a :):
```
=head2 convert_time_to_hours( $hh_mm_time )

Given a time in HH::MM format (e.g. 2:15 or 02:15), return the number of
hours as a decimal (e.g. 2.25).

Example:

  my $hours = $t->convert_time_to_hours( '2:15' );
  # $hours == 2.25

=cut

sub convert_time_to_hours {
    my ( $time ) = @_;

    my $hours = 0;
    my $minutes = 0;
    if ( $time =~ /([0-9]+):([0-9]+)/ ) {
        $hours = $1;
        $minutes = $2;
    } else {
        die "Time duration in incorrect format, must be HH:MM: $time";
    }

    my $numeric_time = $hours + $minutes/60;

    return $numeric_time;
}

```

**Comment by cloudily** [comment]
Resolved via 14975cda1db6b5e8e552376b943c99c2fc1dd6c1
